# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Julie Bacon
email: julieebacon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Julie. I'm an engineer based in Washington, D.C. with a passion for the web, empowering women in tech, and cooking. I work on the Internet at iStrategyLabs as a Front End Developer, building interactive experiences for some of the world's biggest brands.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juliebaconator
github_username:  j-baconator

sass:
    sass_dir: assets/_sass

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
